config/routes.rb
Rails.application.routes.draw do

  root 'users#show'
  get 'users/my_competitions'
  get 'users/my_groups'
  resources :groups, except: %i[destroy]
  resources :competitions, except: %i[destroy]
  resources :goals, only: %i[index new create]
  resources :users, except: %i[index destroy]
  resource :session, only: %i[new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/competition.rb
class Competition < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :goalings, dependent: :destroy
  has_many :goals, through: :goalings
  has_one_attached :image

  before_save :downcase_fields
  before_create :name_exists?

  scope :competitions_goals_count, lambda {
    joins(:goals).select(
      'competitions.*, SUM(goals.amount) AS goals_count'
    ).group('competitions.id')
  }

  def downcase_fields
    name.downcase!
  end

  def name_exists?
    return if current_user.competitions.where(name: name).empty?

    errors.add(:base, 'Competition already exists')
    throw(:abort)
  end

  def current_user
    User.find(user_id)
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :require_login
  before_action :set_competition, only: %i[show edit update]
  def index
    @competitions = current_user.competitions.competitions_goals_count.includes(image_attachment: :blob)
  end

  def new
    @competition = current_user.competitions.build
  end

  def create
    @competition = current_user.competitions.build(competition_params)
    if @competition.save
      redirect_to @competition, notice: 'New Competition added'
    else
      render :new
    end
  end

  def show
    @goals = @competition.goals.latest
    @total_goals = @competition.goals.sum_goals
  end

  def edit; end

  def update
    if @competition.update(competition_params)
      redirect_to @competition, notice: 'Competition Updated'
    else
      render :edit
    end
  end

  def destroy
    @competition.destroy
    redirect_to competitions_path
  end

  private

  def set_competition
    @competition = current_user.competitions.find(params[:id])
  end

  def competition_params
    params.require(:competition).permit(:id, :name, :image)
  end

  def require_login
    redirect_to new_session_path unless session[:user_id]
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_competition.html.erb
<div id="competitions">
    <a href="<%= competition_path(competition) %>" class="goal-items">
      <% image = competition.image.attached? ? url_for(competition.image): 'https://via.placeholder.com/60'%>
      <div class="thumbnail_image" style="background-image:url(&quot;<%= image %>&quot;) ">
      </div>
      <div class="goal-item-info">
        <p class="goal-item-info-top">
          <span class="goal-name"><%= competition.name.capitalize %></span>
          <span class="group-goals">Scored: <%= competition.goals_count %></span>
        </p>
      </div>
    </a>
</div>

app/views/competitions/_competitions.html.erb
<div id="competitions">
  <% @competitions.each do |competition| %>
    <a href="<%= competition_path(competition) %>" class="goal-items">
      <% image = competition.image.attached? ? url_for(competition.image): 'https://via.placeholder.com/60'%>
      <div class="thumbnail_image" style="background-image:url(&quot;<%= image %>&quot;) ">
      </div>
      <div class="goal-item-info">
        <p class="goal-item-info-top">
          <span class="goal-name"><%= competition.name.capitalize %></span>
          <span class="group-goals">Scored: <%= competition.goals_count %></span>
        </p>
      </div>
    </a>
  <% end %>
</div>

app/views/competitions/_form.html.erb
<%= form_with model: @competition do |f| %>
  <%= display_form_errors(@competition) %>

  <div class="field">
    <%= f.text_field :name, placeholder: :name %>
  </div>

  <label for="image" class="field-group-label"> Add Image</label>
  <div class="field">
    <%= f.file_field :image %>
  </div>

  <div class="form-btn-wrapper bg-sec">
    <%= f.submit "#{locals[:submit_btn_text]}", class: 'form-btn bg-sec' %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1 class="form-title">Edit Competition</h1>
<%= render "form", locals:{submit_btn_text: 'Update'} %>

app/views/competitions/index.html.erb
<h1 class="form-title">Grouped By Competitions</h1>
<%= render "goals/menu" %>
<%= no_competiton_message %>
<%= render partial: "competition", collection: @competitions %>

app/views/competitions/new.html.erb
<h1 class="form-title">New Competition</h1>
<%= render "form", locals:{submit_btn_text: 'Create Group'} %>

app/views/competitions/show.html.erb
<div class="profile-wrapper group-wrapper">
    <% image = @competition.image.attached? ? url_for(@competition.image): 'https://via.placeholder.com/150'%>
  <p class="profile-image-wrapper" style="background-image:url(&quot;<%= image %>&quot;) ">
  </p>
  <div class="profile-details">
    <p class="group-name"> <%= @competition.name %> </p>
    <p class="group-goals">
      <%= pluralize(@total_goals, "goal")%>
    </p>
    <%= link_to "Edit", edit_competition_path(@competition), class: "edit-group" %>
  </div>
</div>
<h1 class="form-title"> Goals </p>
<%= render partial: "goals/goal", collection: @goals %>