config/routes.rb
Rails.application.routes.draw do

  root 'users#show'
  get 'users/my_competitions'
  get 'users/my_groups'
  resources :groups, except: %i[destroy]
  resources :competitions, except: %i[destroy]
  resources :goals, only: %i[index new create]
  resources :users, except: %i[index destroy]
  resource :session, only: %i[new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 2..30 }

  belongs_to :user
  has_many :scorings, dependent: :destroy
  has_many :goals, through: :scorings
  has_one_attached :image

  before_save :downcase_fields
  before_create :name_exists?

  scope :groups_goals_count, lambda {
    joins(:goals).select(
      'groups.*, SUM(goals.amount) AS goals_count'
    ).group('groups.id')
  }

  def downcase_fields
    name.downcase!
  end

  def name_exists?
    return if current_user.groups.where(name: name).empty?

    errors.add(:base, 'Style already exists')
    throw(:abort)
  end

  def current_user
    User.find(user_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login
  before_action :set_group, only: %i[show edit update]
  def index
    @groups = current_user.groups.groups_goals_count.includes(image_attachment: :blob)
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to @group, notice: 'Goal Style Added'
    else
      render :new
    end
  end

  def show
    @goals = @group.goals.latest
    @total_goals = @group.goals.sum_goals
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Goal Style Updated'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def set_group
    @group = current_user.groups.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:id, :name, :image)
  end

  def require_login
    redirect_to new_session_path unless session[:user_id]
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group do |f| %>
 <%= display_form_errors(@group) %>

  <div class="field">
    <%= f.text_field :name, placeholder: :name, required: true %>
  </div>

  <label for="image" class="field-group-label"> Choose Image</label>
  <div class="field">
    <%= f.file_field :image, required: true %>
  </div>

  <div class="form-btn-wrapper bg-sec">
    <%= f.submit "#{locals[:submit_btn_text]}", class: 'form-btn bg-sec' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="groups">
  <a href="<%= group_path(group) %>" class="goal-items">
    <% image = group.image.attached? ? url_for(group.image): 'https://via.placeholder.com/60'%>
    <div class="thumbnail_image" style="background-image:url(&quot;<%= image %>&quot;) ">
    </div>
    <div class="goal-item-info">
      <p class="goal-item-info-top">
        <span class="goal-name"><%= group.name.capitalize %></span>
        <span class="group-goals">Scored: <%= group.goals_count %></span>
      </p>
    </div>
  </a>
</div>

app/views/groups/_groups.html.erb
<div id="groups">
  <% @groups.each do |group| %>
  <a href="<%= group_path(group) %>" class="goal-items">
    <% image = group.image.attached? ? url_for(group.image): 'https://via.placeholder.com/60'%>
    <div class="thumbnail_image" style="background-image:url(&quot;<%= image %>&quot;) ">
    </div>
    <div class="goal-item-info">
      <p class="goal-item-info-top">
        <span class="goal-name"><%= group.name.capitalize %></span>
        <span class="group-goals">Scored: <%= group.goals_count %></span>
      </p>
    </div>
  </a>
<% end %>
</div>

app/views/groups/edit.html.erb
<h1 class="form-title">Edit Group</h1>
<%= render "form", locals:{submit_btn_text: 'Update'} %>

app/views/groups/index.html.erb
<h1 class="form-title">Goals Grouped By Style</h1>
<%= render "goals/menu" %>
<%= no_group_message %>
<%= render partial: "group", collection: @groups %>

app/views/groups/new.html.erb
<h1 class="form-title">New Goal Style</h1>
<%= render "form", locals:{submit_btn_text: 'Create Group'} %>

app/views/groups/show.html.erb
<div class="profile-wrapper group-wrapper">
    <% image = @group.image.attached? ? url_for(@group.image): 'https://via.placeholder.com/150'%>
  <p class="profile-image-wrapper" style="background-image:url(&quot;<%= image %>&quot;) ">
  </p>
  <div class="profile-details">
    <p class="group-name"> <%= @group.name %> </p>
    <p class="group-goals">
      <%= pluralize(@total_goals, "goal")%>
    </p>
    <%= link_to "Edit", edit_group_path(@group), class: "edit-group" %>
  </div>
</div>
<h1 class="form-title"> Goals </p>
<%= render partial: "goals/goal", collection: @goals %>