config/routes.rb
Rails.application.routes.draw do

  root 'users#show'
  get 'users/my_competitions'
  get 'users/my_groups'
  resources :groups, except: %i[destroy]
  resources :competitions, except: %i[destroy]
  resources :goals, only: %i[index new create]
  resources :users, except: %i[index destroy]
  resource :session, only: %i[new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: 6..20 }

  has_many :groups, dependent: :destroy
  has_many :goals, dependent: :destroy
  has_many :competitions, dependent: :destroy
  has_one_attached :image

  before_save :downcase_fields
  before_create :name_exists?

  def downcase_fields
    name.downcase!
  end

  def name_exists?
    return if User.where(name: name).empty?

    errors.add(:base, 'Name is taken')
    throw(:abort)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: %i[index new create]
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  def show
    @user = current_user
    @goals = current_user.goals.latest
    @total_goals = current_user.goals.sum_goals
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.save
      redirect_to @user, notice: 'Profile Updated!'
    else
      render :edit
    end
  end

  def my_competitions
    @user = current_user
    @competitions = current_user.competitions.competitions_goals_count.includes(image_attachment: :blob)
    @total_goals = current_user.goals.sum_goals
  end

  def my_groups
    @user = current_user
    @groups = current_user.groups.groups_goals_count.includes(image_attachment: :blob)
    @total_goals = current_user.goals.sum_goals
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :image)
  end

  def require_login
    redirect_to new_session_path unless session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= display_form_errors(@user) %>
  <div class="field">
    <%= f.text_field :name, placeholder: :name, required: true %>
  </div>

  <label for="image" class="field-group-label"> Profile Image</label>
  <div class="field">
    <%= f.file_field :image, required: true %>
  </div>

  <div class="form-btn-wrapper bg-sec">
    <%= f.submit "#{locals[:submit_btn_text]}", class: 'form-btn bg-sec' %>
  </div>
<% end %>

app/views/users/_menu.html.erb
<div class="profile-wrapper">
  <% image = @user.image.attached? ? url_for(@user.image): 'https://via.placeholder.com/150'%>
  <p class="profile-image-wrapper" style="background-image:url(&quot;<%= image %>&quot;) ">
  </p>
  <div class="profile-details">
    <p class="profile-name"> <%= @user.name %> </p>
    <p class="profile-goals">Goals Scored: <b class="profile-goals-number"><%= @total_goals%></b></p>
  </div>
</div>
<div class="profile-menu row">
  <p class="profile-menu-items ">
    <a href="<%= edit_user_path(@user) %>"><i class="fas fa-cog"></i>&nbsp;&nbsp;&nbsp;Profile Settings</a>
  </p>
  <p class="profile-menu-items ">
    <a href="<%= goals_path%>"><i class="far fa-futbol"></i></i>&nbsp;&nbsp;&nbsp;Goals</a>
  </p>
  <p class="profile-menu-items">
    <a href="<%= groups_path %>"><i class="fas fa-border-style"></i>&nbsp;&nbsp;&nbsp;Goal Styles</a>
  </p>
  <p class="profile-menu-items">
    <a href="<%= competitions_path %>"><i class="fas fa-trophy"></i>&nbsp;&nbsp;&nbsp;Competitions</a>
  </p>
</div>

app/views/users/edit.html.erb
<h1 class="form-title">Edit Profile</h1>
<%= render "form", locals:{submit_btn_text: 'Update'} %>

app/views/users/index.html.erb
<% @users.each do |user| %>
 <p> <%= user.name%> </p>
<% end %>

app/views/users/my_competitions.html.erb
<%= render "menu" %>
<h1 class="form-title"> Goals By Competition </h2>
<%= render partial: "competitions/competition", collection: @competitions %>

app/views/users/my_groups.html.erb
<%= render "menu" %>
<h1 class="form-title"> Goals By Style</h2>
<%= render partial: "groups/group", collection: @groups %>

app/views/users/new.html.erb
<h1 class="form-title">Create Account</h1>
<%= render "form", locals:{submit_btn_text: 'Sign Up'} %>

app/views/users/show.html.erb
<%= render "menu" %>