config/routes.rb
Rails.application.routes.draw do

  root 'users#show'
  get 'users/my_competitions'
  get 'users/my_groups'
  resources :groups, except: %i[destroy]
  resources :competitions, except: %i[destroy]
  resources :goals, only: %i[index new create]
  resources :users, except: %i[index destroy]
  resource :session, only: %i[new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="main-nav">
  <div class="left-nav">
    <%= link_to image_tag("actra-wh-01.png", width: 80), root_path %>
    <%= link_to "NEW COMPETITION", new_competition_path %>
    <%= link_to "NEW GOAL STYLE", new_group_path %>
    <%= link_to "GOALS", goals_path %>
    <%= link_to "ADD GOAL", new_goal_path %>
  </div>
  <div class="right-nav">
    <%= display_login_navigation %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actra</title>
    <%= favicon_link_tag asset_path('fav.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= display_notice %>
    <%= display_errors %>
    <main class="main-wrapper">
      <%= yield %>
    </main>
  </body>
</html>